# Generated by Django 4.2.4 on 2023-10-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categary',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
