# Generated by Django 4.2.4 on 2023-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_homecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='blog_heading_body',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='blog_heading',
            field=models.CharField(max_length=255),
        ),
    ]
